# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: camera.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='camera.proto',
  package='omnividi.camera',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x63\x61mera.proto\x12\x0fomnividi.camera\"\x85\x03\n\x0b\x43\x61meraFrame\x12\x14\n\x0ctimestamp_ns\x18\x01 \x01(\x04\x12\x0c\n\x04rows\x18\x02 \x01(\r\x12\x0c\n\x04\x63ols\x18\x03 \x01(\r\x12\x10\n\x08\x63hannels\x18\x04 \x01(\r\x12\x0c\n\x04step\x18\x05 \x01(\r\x12*\n\x05\x63odec\x18\x06 \x01(\x0e\x32\x1b.omnividi.camera.VideoCodec\x12\x10\n\x08\x63odec_id\x18\x07 \x01(\r\x12\x11\n\tcodec_tag\x18\x08 \x01(\r\x12\x13\n\x0bvideo_width\x18\t \x01(\r\x12\x14\n\x0cvideo_height\x18\n \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x0b \x01(\x0c\x12\x33\n\tdata_type\x18\x0c \x01(\x0e\x32\x19.omnividi.camera.DataType:\x05UINT8\x12\x33\n\ncolor_type\x18\r \x01(\x0e\x32\x1a.omnividi.camera.ColorType:\x03\x42GR\x12\x30\n\x0b\x64\x61ta_format\x18\x0e \x01(\x0e\x32\x1b.omnividi.camera.DataFormat*S\n\x08\x44\x61taType\x12\t\n\x05UINT8\x10\x01\x12\n\n\x06UINT16\x10\x02\x12\n\n\x06UINT32\x10\x03\x12\n\n\x06UINT64\x10\x04\x12\x0b\n\x07\x46LOAT32\x10\x05\x12\x0b\n\x07\x46LOAT64\x10\x06*\x1e\n\tColorType\x12\x08\n\x04GRAY\x10\x01\x12\x07\n\x03\x42GR\x10\x02*%\n\nDataFormat\x12\n\n\x06OPENCV\x10\x01\x12\x0b\n\x07\x45NCODED\x10\x02*\x7f\n\nVideoCodec\x12\x11\n\rCODEC_UNKNOWN\x10\x00\x12\x0e\n\nCODEC_H264\x10\x01\x12\x0e\n\nCODEC_H265\x10\x02\x12\x0f\n\x0b\x43ODEC_MPEG4\x10\x03\x12\x0f\n\x0b\x43ODEC_MJPEG\x10\x04\x12\r\n\tCODEC_VP8\x10\x05\x12\r\n\tCODEC_VP9\x10\x06'
)

_DATATYPE = _descriptor.EnumDescriptor(
  name='DataType',
  full_name='omnividi.camera.DataType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UINT8', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UINT16', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UINT32', index=2, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UINT64', index=3, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FLOAT32', index=4, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FLOAT64', index=5, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=425,
  serialized_end=508,
)
_sym_db.RegisterEnumDescriptor(_DATATYPE)

DataType = enum_type_wrapper.EnumTypeWrapper(_DATATYPE)
_COLORTYPE = _descriptor.EnumDescriptor(
  name='ColorType',
  full_name='omnividi.camera.ColorType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GRAY', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BGR', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=510,
  serialized_end=540,
)
_sym_db.RegisterEnumDescriptor(_COLORTYPE)

ColorType = enum_type_wrapper.EnumTypeWrapper(_COLORTYPE)
_DATAFORMAT = _descriptor.EnumDescriptor(
  name='DataFormat',
  full_name='omnividi.camera.DataFormat',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OPENCV', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ENCODED', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=542,
  serialized_end=579,
)
_sym_db.RegisterEnumDescriptor(_DATAFORMAT)

DataFormat = enum_type_wrapper.EnumTypeWrapper(_DATAFORMAT)
_VIDEOCODEC = _descriptor.EnumDescriptor(
  name='VideoCodec',
  full_name='omnividi.camera.VideoCodec',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CODEC_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CODEC_H264', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CODEC_H265', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CODEC_MPEG4', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CODEC_MJPEG', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CODEC_VP8', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CODEC_VP9', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=581,
  serialized_end=708,
)
_sym_db.RegisterEnumDescriptor(_VIDEOCODEC)

VideoCodec = enum_type_wrapper.EnumTypeWrapper(_VIDEOCODEC)
UINT8 = 1
UINT16 = 2
UINT32 = 3
UINT64 = 4
FLOAT32 = 5
FLOAT64 = 6
GRAY = 1
BGR = 2
OPENCV = 1
ENCODED = 2
CODEC_UNKNOWN = 0
CODEC_H264 = 1
CODEC_H265 = 2
CODEC_MPEG4 = 3
CODEC_MJPEG = 4
CODEC_VP8 = 5
CODEC_VP9 = 6



_CAMERAFRAME = _descriptor.Descriptor(
  name='CameraFrame',
  full_name='omnividi.camera.CameraFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp_ns', full_name='omnividi.camera.CameraFrame.timestamp_ns', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rows', full_name='omnividi.camera.CameraFrame.rows', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cols', full_name='omnividi.camera.CameraFrame.cols', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='channels', full_name='omnividi.camera.CameraFrame.channels', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='step', full_name='omnividi.camera.CameraFrame.step', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='codec', full_name='omnividi.camera.CameraFrame.codec', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='codec_id', full_name='omnividi.camera.CameraFrame.codec_id', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='codec_tag', full_name='omnividi.camera.CameraFrame.codec_tag', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='video_width', full_name='omnividi.camera.CameraFrame.video_width', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='video_height', full_name='omnividi.camera.CameraFrame.video_height', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='omnividi.camera.CameraFrame.data', index=10,
      number=11, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_type', full_name='omnividi.camera.CameraFrame.data_type', index=11,
      number=12, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='color_type', full_name='omnividi.camera.CameraFrame.color_type', index=12,
      number=13, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_format', full_name='omnividi.camera.CameraFrame.data_format', index=13,
      number=14, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=423,
)

_CAMERAFRAME.fields_by_name['codec'].enum_type = _VIDEOCODEC
_CAMERAFRAME.fields_by_name['data_type'].enum_type = _DATATYPE
_CAMERAFRAME.fields_by_name['color_type'].enum_type = _COLORTYPE
_CAMERAFRAME.fields_by_name['data_format'].enum_type = _DATAFORMAT
DESCRIPTOR.message_types_by_name['CameraFrame'] = _CAMERAFRAME
DESCRIPTOR.enum_types_by_name['DataType'] = _DATATYPE
DESCRIPTOR.enum_types_by_name['ColorType'] = _COLORTYPE
DESCRIPTOR.enum_types_by_name['DataFormat'] = _DATAFORMAT
DESCRIPTOR.enum_types_by_name['VideoCodec'] = _VIDEOCODEC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CameraFrame = _reflection.GeneratedProtocolMessageType('CameraFrame', (_message.Message,), {
  'DESCRIPTOR' : _CAMERAFRAME,
  '__module__' : 'camera_pb2'
  # @@protoc_insertion_point(class_scope:omnividi.camera.CameraFrame)
  })
_sym_db.RegisterMessage(CameraFrame)


# @@protoc_insertion_point(module_scope)
